//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DBTables
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Tbl_SlideImage
    {
        public int SlideId { get; set; }
        [Required]
        public string SlideTitle { get; set; }
        [Required]
        [DisplayName("Upload File")]
        public string SlideImage { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
